### ISSUE TITLE
Equivalent to `zinbwave::getPi`?

### ISSUE THREAD

**Issue by cvanderaa** [fedeago/NewWave#13]
Hello, 

I saw that `zinbwave::getMu` becomes `NewWave::newMu`, so I was wondering if there is an equivalent to `zinbwave::getPi`. `NewWave::newPi` does not seems to be exported. 

Thanks in advance!

**Comment by Federico-Agostinis** [comment]
Hello

There is not newPi because NewWave do not have Pi parameter.

In Zinbwave Pi matrix is needed to model the proportion of 0 and the related parameter in the zero inflated negative binomial 
model but NewWave uses a Negative binomial model and so it do not model the proportion of 0 with a specific parameter.

Regards

**Comment by cvanderaa** [comment]
Thanks a lot for your quick reply!
